#%RAML 0.8
---
title: companionize
documentation:
    - title: Companionize REST API
      content: |
        Welcome to the project API.
baseUri: http://{host}:{port}/{version}
version: v1
mediaType: application/json
protocols: [HTTP]

/register:
    displayName: Register
    post:
        description: Create a new user
        body:
            application/json:
                schema: !include register.json

/activity:
  displayName: Register Activity
  get:
      description: Get all Activities
  post:
      description: Create activity
      body:
        application/json:
          schema: !include activity.json
  /{id}:
      displayName: "Subscription"
      get:
          description: Get a particular activity
      delete:
          description: Delete a particular activity
